variable "project" {
  type = string
}

variable "vpc_id" {
  type = string
}

variable "private_subnet_ids" {
  type = list(string)
}

variable "allowed_security_group_ids" {
  description = "Security groups (ECS task SGs) allowed to reach MariaDB on 3306."
  type        = list(string)
}

variable "engine_version" {
  type    = string
  default = "10.11"
}

variable "instance_class" {
  type    = string
  default = "db.t4g.micro"
}

variable "allocated_storage" {
  type    = number
  default = 20
}

variable "db_name" {
  type    = string
  default = "steet_bites"
}

variable "username" {
  type    = string
  default = "steet_bites"
}

variable "password" {
  description = "Generated by random_password in environments/prod/secrets.tf and stored in Secrets Manager, never hardcoded."
  type        = string
  sensitive   = true
}

variable "multi_az" {
  description = "false = single-AZ (first-cut default). Flip to true when a real production launch needs the availability guarantee — no restructuring needed, just this variable."
  type        = bool
  default     = false
}
